table 'Channel Table'
	lineageTag: 57725a61-ebf8-45c3-a6fe-66c4276c6d90

	measure '% Revenue Campaign Responders Growth' =
			
			DIVIDE(
			    [Revenue Campaign Responders] - [Revenue Campaign Responders Prev Month],
			    [Revenue Campaign Responders Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Growth & Time Intelligence\Revenue Responders
		lineageTag: 8c189f50-a36f-4409-9ec2-6283011dc320

	column Channel
		lineageTag: 9c4425ef-770d-47bb-a121-5d938fa13d2c
		summarizeBy: none
		isNameInferred
		sourceColumn: [Channel]

		annotation SummarizationSetBy = Automatic

	partition 'Channel Table' = calculated
		mode: import
		source =
				
				DATATABLE(
				    "Channel", STRING,
				    {
				        {"Web"},
				        {"Store"},
				        {"Catalog"},
				        {"Deals"}
				    }
				)

	annotation PBI_Id = 5a708f8b8ca74d01a7bafa816b34d942

