table marketing_campaign
	lineageTag: cf001cf7-a079-4546-a5a6-a6ffb7cef318

	column ID
		dataType: int64
		formatString: 0
		lineageTag: e8c2799b-0efa-46fb-8f8e-f3786e193458
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Year_Birth
		dataType: int64
		formatString: 0
		lineageTag: a00a22f6-7630-432b-9870-265119a19dfc
		summarizeBy: sum
		sourceColumn: Year_Birth

		annotation SummarizationSetBy = Automatic

	column Income
		dataType: int64
		formatString: 0
		lineageTag: 967cfe78-9c3e-444d-8302-19229215b6e3
		summarizeBy: sum
		sourceColumn: Income

		annotation SummarizationSetBy = Automatic

	column Kidhome
		dataType: int64
		formatString: 0
		lineageTag: 66ac99e4-6d03-4c7b-8808-ebd3176b1d67
		summarizeBy: sum
		sourceColumn: Kidhome

		annotation SummarizationSetBy = Automatic

	column Teenhome
		dataType: int64
		formatString: 0
		lineageTag: 7b209575-4bdb-431c-bf67-b1cd7da5bd79
		summarizeBy: sum
		sourceColumn: Teenhome

		annotation SummarizationSetBy = Automatic

	column Dt_Customer
		dataType: dateTime
		formatString: Long Date
		lineageTag: 29a31dfc-e822-415d-bee8-5fc56e784f00
		summarizeBy: none
		sourceColumn: Dt_Customer

		variation Variación
			isDefault
			relationship: 1a9f4baf-5b1e-4eb8-aff6-2af4ee7db45c
			defaultHierarchy: LocalDateTable_3ec1e116-f95a-4172-a726-a2a91036956d.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Recency
		dataType: int64
		formatString: 0
		lineageTag: 36b80d30-ece0-42b1-9a6f-355ca1f98bd1
		summarizeBy: sum
		sourceColumn: Recency

		annotation SummarizationSetBy = Automatic

	column MntWines
		dataType: int64
		formatString: 0
		lineageTag: e56d4831-8978-4a6c-b5c4-89fd13230bd5
		summarizeBy: sum
		sourceColumn: MntWines

		annotation SummarizationSetBy = Automatic

	column MntFruits
		dataType: int64
		formatString: 0
		lineageTag: 4f9174be-07b6-42fa-aab7-9a4ba70fa220
		summarizeBy: sum
		sourceColumn: MntFruits

		annotation SummarizationSetBy = Automatic

	column MntMeatProducts
		dataType: int64
		formatString: 0
		lineageTag: 9637ed21-e746-44bd-89b1-775c07ad7286
		summarizeBy: sum
		sourceColumn: MntMeatProducts

		annotation SummarizationSetBy = Automatic

	column MntFishProducts
		dataType: int64
		formatString: 0
		lineageTag: 7f4cb60f-a1ff-43cd-9e30-00bc508ddd13
		summarizeBy: sum
		sourceColumn: MntFishProducts

		annotation SummarizationSetBy = Automatic

	column MntSweetProducts
		dataType: int64
		formatString: 0
		lineageTag: d77044e8-a656-4ea6-a338-7efcf078bd65
		summarizeBy: sum
		sourceColumn: MntSweetProducts

		annotation SummarizationSetBy = Automatic

	column MntGoldProds
		dataType: int64
		formatString: 0
		lineageTag: 4689c6bd-05ba-4921-9431-847470f449d1
		summarizeBy: sum
		sourceColumn: MntGoldProds

		annotation SummarizationSetBy = Automatic

	column NumDealsPurchases
		dataType: int64
		formatString: 0
		lineageTag: 14a80b01-beb1-4428-b5eb-54030b89c305
		summarizeBy: sum
		sourceColumn: NumDealsPurchases

		annotation SummarizationSetBy = Automatic

	column NumWebPurchases
		dataType: int64
		formatString: 0
		lineageTag: 8581f40c-1861-48fa-b5db-b3f7f5622862
		summarizeBy: sum
		sourceColumn: NumWebPurchases

		annotation SummarizationSetBy = Automatic

	column NumCatalogPurchases
		dataType: int64
		formatString: 0
		lineageTag: 47146287-408b-4902-b66b-02af11a493fc
		summarizeBy: sum
		sourceColumn: NumCatalogPurchases

		annotation SummarizationSetBy = Automatic

	column NumStorePurchases
		dataType: int64
		formatString: 0
		lineageTag: 161f53e5-8081-4467-b333-5a2abd1605ff
		summarizeBy: sum
		sourceColumn: NumStorePurchases

		annotation SummarizationSetBy = Automatic

	column NumWebVisitsMonth
		dataType: int64
		formatString: 0
		lineageTag: ff8c05a9-6484-4b71-a742-8ae62fa948dc
		summarizeBy: sum
		sourceColumn: NumWebVisitsMonth

		annotation SummarizationSetBy = Automatic

	column AcceptedCmp3
		dataType: int64
		formatString: 0
		lineageTag: 7cd5ac40-5af1-4ead-a6bf-38fed0c11043
		summarizeBy: sum
		sourceColumn: AcceptedCmp3

		annotation SummarizationSetBy = Automatic

	column AcceptedCmp4
		dataType: int64
		formatString: 0
		lineageTag: b2d4f448-c0be-4bae-8fa8-cb4e7dd7e214
		summarizeBy: sum
		sourceColumn: AcceptedCmp4

		annotation SummarizationSetBy = Automatic

	column AcceptedCmp5
		dataType: int64
		formatString: 0
		lineageTag: 57314c73-87f7-4503-ae95-6c3ca02015e6
		summarizeBy: sum
		sourceColumn: AcceptedCmp5

		annotation SummarizationSetBy = Automatic

	column AcceptedCmp1
		dataType: int64
		formatString: 0
		lineageTag: 7679423d-2e21-4465-95a2-ae2618c8c21f
		summarizeBy: sum
		sourceColumn: AcceptedCmp1

		annotation SummarizationSetBy = Automatic

	column AcceptedCmp2
		dataType: int64
		formatString: 0
		lineageTag: 0b2ca6bd-933b-457c-acd7-ce85d10318bd
		summarizeBy: sum
		sourceColumn: AcceptedCmp2

		annotation SummarizationSetBy = Automatic

	column Complain
		dataType: int64
		formatString: 0
		lineageTag: 108b08eb-c8c2-4f7a-91b7-03f66403c348
		summarizeBy: sum
		sourceColumn: Complain

		annotation SummarizationSetBy = Automatic

	column Response
		dataType: int64
		formatString: 0
		lineageTag: 781661b2-bd5a-4265-a5fc-8bcc0c831c49
		summarizeBy: sum
		sourceColumn: Response

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: cac39331-8f40-47bf-b5ed-eb49585bf611
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Age_segment
		dataType: string
		lineageTag: 209cc2f0-442e-42de-9b63-921571b4ed87
		summarizeBy: none
		sourceColumn: Age_segment

		annotation SummarizationSetBy = Automatic

	column Marital_Status
		dataType: string
		lineageTag: c2a5654e-b3c3-48ad-80cd-2a37d152c629
		summarizeBy: none
		sourceColumn: Marital_Status

		annotation SummarizationSetBy = Automatic

	column Education_level
		dataType: string
		lineageTag: 563846ed-e8ef-433e-bb9c-d699302bd7f5
		summarizeBy: none
		sourceColumn: Education_level

		annotation SummarizationSetBy = Automatic

	column Total_Spending
		dataType: decimal
		formatString: "S/"\ #,0.###############;-"S/"\ #,0.###############;"S/"\ #,0.###############
		lineageTag: 2ab2b562-974d-4562-bccd-1a51ce33ad5f
		summarizeBy: sum
		sourceColumn: Total_Spending

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	column Total_Purchases
		dataType: int64
		formatString: 0
		lineageTag: d8e9fc5e-0325-41fc-b5b8-73f7b5d3e05f
		summarizeBy: sum
		sourceColumn: Total_Purchases

		annotation SummarizationSetBy = Automatic

	column TotalCampaignAccepted
		dataType: int64
		formatString: 0
		lineageTag: ffd6b5d9-c877-442f-b4eb-42e94e51d16b
		summarizeBy: sum
		sourceColumn: TotalCampaignAccepted

		annotation SummarizationSetBy = Automatic

	column Engagement_Score
		dataType: int64
		formatString: 0
		lineageTag: e039cde7-e955-4802-bb0b-796fffc3e7d8
		summarizeBy: sum
		sourceColumn: Engagement_Score

		annotation SummarizationSetBy = Automatic

	column Total_Children
		dataType: int64
		formatString: 0
		lineageTag: aa3b720e-45f4-4917-b9e2-6a5171e4b0c1
		summarizeBy: sum
		sourceColumn: Total_Children

		annotation SummarizationSetBy = Automatic

	column Engagement_Score_segment
		dataType: string
		lineageTag: 4eb366d1-0443-4aaf-8a77-9b2b2b69162e
		summarizeBy: none
		sourceColumn: Engagement_Score_segment

		annotation SummarizationSetBy = Automatic

	partition marketing_campaign = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("C:\Users\Juan Manuel\Documents\PERSONALES\PROYECTOS\Power-BI---crm-customer-experience-analytics\data\raw\marketing_campaign.csv"),[Delimiter="	", Columns=29, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID", Int64.Type}, {"Year_Birth", Int64.Type}, {"Education", type text}, {"Marital_Status", type text}, {"Income", Int64.Type}, {"Kidhome", Int64.Type}, {"Teenhome", Int64.Type}, {"Dt_Customer", type date}, {"Recency", Int64.Type}, {"MntWines", Int64.Type}, {"MntFruits", Int64.Type}, {"MntMeatProducts", Int64.Type}, {"MntFishProducts", Int64.Type}, {"MntSweetProducts", Int64.Type}, {"MntGoldProds", Int64.Type}, {"NumDealsPurchases", Int64.Type}, {"NumWebPurchases", Int64.Type}, {"NumCatalogPurchases", Int64.Type}, {"NumStorePurchases", Int64.Type}, {"NumWebVisitsMonth", Int64.Type}, {"AcceptedCmp3", Int64.Type}, {"AcceptedCmp4", Int64.Type}, {"AcceptedCmp5", Int64.Type}, {"AcceptedCmp1", Int64.Type}, {"AcceptedCmp2", Int64.Type}, {"Complain", Int64.Type}, {"Z_CostContact", Int64.Type}, {"Z_Revenue", Int64.Type}, {"Response", Int64.Type}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "Age", each Date.Year(DateTime.LocalNow()) - [Year_Birth]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Age", Int64.Type}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado1", "Age_segment", each if [Age] >= 60 then "Senior" else if [Age] >= 45 then "Mature" else if [Age] >= 30 then "Adult" else if [Age] >= 18 then "Young" else "Under Age"),
				    #"Filas filtradas" = Table.SelectRows(#"Columna condicional agregada", each true),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Filas filtradas",{{"Marital_Status", "Marital_Status_OG"}}),
				    #"Columna condicional agregada1" = Table.AddColumn(#"Columnas con nombre cambiado", "Marital_Status", each if [Marital_Status_OG] = "Single" then "Single" else if [Marital_Status_OG] = "Alone" then "Single" else if [Marital_Status_OG] = "Together" then "Couple" else if [Marital_Status_OG] = "Married" then "Couple" else if [Marital_Status_OG] = "Divorced" then "Divorced" else if [Marital_Status_OG] = "Widow" then "Widow" else if [Marital_Status_OG] = "Absurd" then "Other" else if [Marital_Status_OG] = "YOLO" then "Other" else "Other"),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Columna condicional agregada1",{"Marital_Status_OG"}),
				    #"Columna condicional agregada2" = Table.AddColumn(#"Columnas quitadas", "Education_level", each if [Education] = "PhD" then "Postgraduate" else if [Education] = "Master" then "Postgraduate" else if [Education] = "Graduation" then "University" else if [Education] = "2n Cycle" then "University" else if [Education] = "Basic" then "Basic" else "Other"),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Columna condicional agregada2",{"Education"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Columnas quitadas1", "Total_Spending", each [MntWines] + [MntFruits] + [MntMeatProducts] + [MntFishProducts] + [MntSweetProducts] + [MntGoldProds]),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"Total_Spending", Currency.Type}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado2", "Total_Purchases", each [NumDealsPurchases] + [NumWebPurchases] + [NumCatalogPurchases] + [NumStorePurchases]),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Personalizada agregada2",{{"Total_Purchases", Int64.Type}}),
				    #"Personalizada agregada3" = Table.AddColumn(#"Tipo cambiado3", "TotalCampaignAccepted", each [AcceptedCmp1] + [AcceptedCmp2] + [AcceptedCmp3] + [AcceptedCmp4] + [AcceptedCmp5]),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Personalizada agregada3",{{"TotalCampaignAccepted", Int64.Type}}),
				    #"Personalizada agregada4" = Table.AddColumn(#"Tipo cambiado4", "Engagement Score", each [Total_Purchases] + [TotalCampaignAccepted]),
				    #"Tipo cambiado5" = Table.TransformColumnTypes(#"Personalizada agregada4",{{"Engagement Score", Int64.Type}}),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Tipo cambiado5",{"Z_CostContact", "Z_Revenue"}),
				    #"Personalizada agregada5" = Table.AddColumn(#"Columnas quitadas2", "Total_Children", each [Kidhome] + [Teenhome]),
				    #"Tipo cambiado6" = Table.TransformColumnTypes(#"Personalizada agregada5",{{"Total_Children", Int64.Type}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado6",{{"Engagement Score", "Engagement_Score"}}),
				    #"Columna condicional agregada3" = Table.AddColumn(#"Columnas con nombre cambiado1", "Engagement_Score_segment", each if [Engagement_Score] >= 21 then "Champions" else if [Engagement_Score] >= 11 then "High Engagement" else if [Engagement_Score] >= 4 then "Medium Engagement" else if [Engagement_Score] >= 1 then "Low Engagement" else "No Engagement"),
				    #"Tipo cambiado7" = Table.TransformColumnTypes(#"Columna condicional agregada3",{{"Engagement_Score_segment", type text}})
				in
				    #"Tipo cambiado7"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

