table Measures_Table
	lineageTag: 052d9a09-08b3-4bce-961b-c937b1ec53cf

	measure 'Total Customers' = DISTINCTCOUNT(FactCustomerMetrics[ID])
		formatString: #,0
		displayFolder: KPIs\Customer KPIs
		lineageTag: 4a60286f-e048-437f-8117-14906c518063

	measure 'Avg Customer Income' = AVERAGE(FactCustomerMetrics[Income])
		formatString: #,0.00
		displayFolder: KPIs\Customer KPIs
		lineageTag: 9b5914a0-37eb-44ed-b4b0-ff3e90104971

	measure 'Avg Customer Age' = AVERAGE(DimCustomer[Age])
		formatString: 0.00
		displayFolder: KPIs\Customer KPIs
		lineageTag: 9a2846c0-05da-48a8-9d4c-639326ea165a

	measure 'Avg Recency' = AVERAGE(FactCustomerMetrics[Recency])
		formatString: 0.00
		displayFolder: KPIs\Customer KPIs
		lineageTag: 983a2658-e481-4184-8fe2-d6fc79488e4f

	measure 'Customers With Children' =
			
			CALCULATE(
			    COUNTROWS(FactCustomerMetrics),
			    FactCustomerMetrics[Total_Children]> 0
			)
		formatString: #,0
		displayFolder: KPIs\Customer KPIs
		lineageTag: 6f366abc-9e93-4f4d-beee-6ba85150e7f9

	measure 'Total Revenue' = SUM(FactCustomerMetrics[Total_Spending])
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: c91166f0-b60a-4003-a879-ae72e73c6913

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Avg Purchase Value' =
			
			DIVIDE(
			    [Total Revenue],
			    [Total Purchases],
			    0
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: 8f1ebe62-01c0-4490-a44a-16735ed0ef8e

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue Engaged Customers' =
			
			CALCULATE(
			    [Total Revenue],
			    FactCustomerMetrics[Engagement_Score] > 0
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: 21151e81-152a-435b-9e17-9ea478d84f58

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue Wines' = SUM(FactCustomerMetrics[MntWines])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: b444a697-6821-4d9c-b76f-86458413a0d4

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Revenue Fruits' = SUM(FactCustomerMetrics[MntFruits])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: cea8d395-ffde-4df9-a4dd-178ffdc165d3

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Revenue Meat' = SUM(FactCustomerMetrics[MntMeatProducts])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: c275650b-e184-4fb3-87fe-b3da7b95460e

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Revenue Fish' = SUM(FactCustomerMetrics[MntFishProducts])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: 24897b1d-42be-4bd5-b40f-51e44669e47c

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Revenue Sweets' = SUM(FactCustomerMetrics[MntSweetProducts])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: d18c1420-9bd1-4b36-953e-02a0f2550f64

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Revenue Gold' = SUM(FactCustomerMetrics[MntGoldProds])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		displayFolder: KPIs\Revenue KPIs
		lineageTag: b555a434-1162-4e92-b816-22c996353dc8

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Purchases' = SUM(FactCustomerMetrics[Total_Purchases])
		formatString: 0.00
		displayFolder: KPIs\Purchase Behavior KPIs
		lineageTag: 5333393d-d1cc-4fb4-8e5a-bc1ed5c61276

	measure 'Avg Purchases Customer' =
			
			DIVIDE(
			    [Total Purchases],
			    [Total Customers]
			    )
		displayFolder: KPIs\Purchase Behavior KPIs
		lineageTag: 71e30ce2-f1b6-4a31-89f0-500fbae3fc7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Web Purchases' = SUM(FactCustomerMetrics[NumWebPurchases])
		formatString: #,0
		displayFolder: KPIs\Purchase Behavior KPIs
		lineageTag: 347fff1e-1b48-4870-9e03-9d7a0cc414e6

	measure 'Store Purchases' = SUM(FactCustomerMetrics[NumStorePurchases])
		formatString: #,0
		displayFolder: KPIs\Purchase Behavior KPIs
		lineageTag: 54cdd7ee-ab97-4d85-a87b-3327c7104aa7

	measure 'Catalog Purchases' = SUM(FactCustomerMetrics[NumCatalogPurchases])
		formatString: #,0
		displayFolder: KPIs\Purchase Behavior KPIs
		lineageTag: 5950b3fc-842b-42ad-a75e-f35a191d2ae4

	measure 'Campaign Responses' = SUM(FactCustomerMetrics[Response])
		formatString: #,0
		displayFolder: KPIs\Marketing Campaign KPIs
		lineageTag: 470dc576-d7b9-4732-9f17-f3f8ddaef74c

	measure 'Campaign Conversion Rate' =
			
			DIVIDE(
			    [Campaign Responses],
			    [Total Customers]
			    )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: KPIs\Marketing Campaign KPIs
		lineageTag: 9bd9b47e-7137-482d-90a9-f3f4f46c3018

	measure 'Total Campaign Accepted' = SUM(FactCustomerMetrics[TotalCampaignAccepted])
		formatString: #,0
		displayFolder: KPIs\Marketing Campaign KPIs
		lineageTag: a04bc006-2707-414a-b4e9-955d43a59e21

	measure 'Avg Campaign Accepted' = AVERAGE(FactCustomerMetrics[TotalCampaignAccepted])
		displayFolder: KPIs\Marketing Campaign KPIs
		lineageTag: 9239dd31-c8fd-4a61-9b2b-29e8c56b7c6c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Campaign Responders' =
			
			CALCULATE(
			    [Total Revenue],
			    FactCustomerMetrics[Response] = 1
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		displayFolder: KPIs\Marketing Campaign KPIs
		lineageTag: 7e44a5ac-db5c-4b3b-a528-d6b0986a57f7

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Avg Engagement' = AVERAGE(FactCustomerMetrics[Engagement_Score])
		displayFolder: KPIs\Engagement KPIs
		lineageTag: 4fa8c169-7199-4656-bdc9-06d48140af78

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'High Engagement Customers' =
			
			CALCULATE(
			    [Total Customers],
			    FactCustomerMetrics[Engagement_Score] >= 11
			)
		formatString: #,0
		displayFolder: KPIs\Engagement KPIs
		lineageTag: 29f18464-726a-4103-8169-6d2d6e39faf4

	measure 'Active Customers' =
			
			CALCULATE(
			    [Total Customers],
			    FactCustomerMetrics[Recency] <= 30
			)
		formatString: #,0
		displayFolder: KPIs\Retention KPIs
		lineageTag: 4006b34a-8cc1-41de-86ac-2eb8c5e188c9

	measure 'At Risk Customers' =
			
			CALCULATE(
			    [Total Customers],
			    FactCustomerMetrics[Recency] > 90
			)
		formatString: #,0
		displayFolder: KPIs\Retention KPIs
		lineageTag: 245500a3-558a-4015-8aae-05f297a99f45

	measure 'Estimated CLV' = [Avg Purchase Value] * [Avg Purchases Customer]
		formatString: "S/"\ #,0.###############;-"S/"\ #,0.###############;"S/"\ #,0.###############
		displayFolder: KPIs\Retention KPIs
		lineageTag: f07ad5ed-7956-445b-a845-443a3aa921ab

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Total Customers Prev Month' =
			
			CALCULATE(
			    [Total Customers],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    ))
		formatString: #,0
		lineageTag: 39fefa91-79df-43c0-bdb6-1956f2509fbb

	measure 'Total Customers Variance' = [Total Customers] - [Total Customers Prev Month]
		formatString: 0
		lineageTag: ee979542-fe23-4525-940e-3c0cd1833921

	measure '% Customer Growth' =
			
			DIVIDE(
			    [Total Customers] - [Total Customers Prev Month],
			    [Total Customers Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 2a4157e5-a1c7-4aa4-bbfc-9737ac2bd697

	measure 'New Customers' =
			
			CALCULATE(
			    [Total Customers],
			    DATESINPERIOD(
			        DimDate[Date],
			        MAX(DimDate[Date]),
			        -1,
			        MONTH
			    )
			)
		formatString: #,0
		lineageTag: d50d9ac6-4e90-4116-8dae-06f47291e9a3

	measure 'Total Revenue Prev Month' =
			
			CALCULATE(
			    [Total Revenue],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 6cb719a8-67d9-4152-a6b2-f137ce5e96cf

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Total Revenue Variance' = [Total Revenue] - [Total Revenue Prev Month]
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: a62d6e78-21c7-4c60-9bf6-4a5fc4b2836a

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% Revenue Growth' =
			
			DIVIDE(
			    [Total Revenue] - [Total Revenue Prev Month],
			    [Total Revenue Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 703cc824-3339-41da-b714-bf986e4dbaf5

	measure ARPC =
			
			DIVIDE(
			    [Total Revenue],
			    [Total Customers]
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 1d97d10c-49fd-4a2c-bbb8-49071ee03ebd

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'High Value Revenue' =
			
			CALCULATE(
			    [Total Revenue],
			    FactCustomerMetrics[Total_Spending] >
			    AVERAGE(FactCustomerMetrics[Total_Spending])
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 8b558a1b-11b6-488f-9d78-1ee870d73d34

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% Revenue High Value' =
			
			DIVIDE(
			    [High Value Revenue],
			    [Total Revenue],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: bac8fcba-cd38-4df9-9d47-306666078963

	measure 'Campaign Conversion Rate Prev Month' =
			
			CALCULATE(
			    [Campaign Conversion Rate],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3607f474-1606-4a8a-90bd-b258d4f64f36

	measure 'Campaign Conversion Rate Variance' = [Campaign Conversion Rate] - [Campaign Conversion Rate Prev Month]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: a9f776f1-eed0-40a1-a35a-58e37af2324e

	measure '% Campaign Conversion Rate Growth' =
			
			DIVIDE(
			    [Campaign Conversion Rate] - [Campaign Conversion Rate Prev Month],
			    [Campaign Conversion Rate Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 177a928e-e66c-4a77-b55c-541b86d3935b

	measure 'Revenue per Response' =
			
			DIVIDE(
			    [Total Revenue],
			    [Campaign Responses]
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: d56bc92b-86e7-446a-8d9e-7329a9b7b19a

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue Selected Category' =
			
			SWITCH(
			    SELECTEDVALUE('Product Category Table'[Category]),
			    "Wines", [Revenue Wines],
			    "Meat", [Revenue Meat],
			    "Fish", [Revenue Fish],
			    "Fruits", [Revenue Fruits],
			    "Sweets", [Revenue Sweets],
			    "Gold", [Revenue Gold]
			)
		formatString: 0
		lineageTag: 97d8149f-6816-4f73-a098-a54acc42a960

	measure 'Avg Customer Income Prev Month' =
			
			CALCULATE(
			    [Avg Customer Income],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a6243561-1dde-4673-bcd1-cf4b0a156fb4

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Median Income' = MEDIAN(FactCustomerMetrics[Income])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7f95eaec-1c34-43b9-a185-314884a1c76d

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% High Income' =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT(FactCustomerMetrics[ID]),
			        FactCustomerMetrics[Income] >= 80000
			    ),
			    [Total Customers]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 2835beef-9acb-4fe8-af6c-c85d000307cf

	measure 'Avg Customer Income Variance' = [Avg Customer Income] - [Avg Customer Income Prev Month]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3e6fda3d-a814-45eb-86af-b2ffe403e142

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% Avg Customer Income Growth' =
			
			DIVIDE(
			    [Avg Customer Income] - [Avg Customer Income Prev Month],
			    [Avg Customer Income Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9817cadc-7b9c-413b-92e5-2eb749617351

	measure 'Avg Customer Age Previous Month' =
			
			CALCULATE(
			    [Avg Customer Age],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00
		lineageTag: c826e9e9-1954-48e2-8184-e9dafe19fdc7

	measure 'Avg Customer Age Variance' = [Avg Customer Age] - [Avg Customer Age Previous Month]
		formatString: 0.00
		lineageTag: 68f9e6d7-6a54-4d78-8375-e012f89f1a7b

	measure '% Avg Customer Age Growth' =
			
			DIVIDE(
			    [Avg Customer Age] - [Avg Customer Age Previous Month],
			    [Avg Customer Age Previous Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 53f7e792-e44a-4749-8f39-e0e79b5d5e77

	measure 'Median Age' = MEDIAN(DimCustomer[Age])
		lineageTag: fadc9310-323e-43d0-93cb-246ad051d1e6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '% Core Age (30-55)' =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT(FactCustomerMetrics[ID]),
			        DimCustomer[Age] >= 30 &&
			        DimCustomer[Age] <= 55
			    ),
			    [Total Customers]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: ff150cb9-61b7-4dc3-bdb7-d7f924b07ee8

	measure 'ARPC Prev Month' =
			
			CALCULATE(
			    [ARPC],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 050ff77b-6971-49f4-b661-fe1008a65cc5

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'ARPC Variance' = [ARPC] - [ARPC Prev Month]
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: b824ede0-9826-4225-9a56-2d9a4a60b4a6

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% ARPC Growth' =
			
			DIVIDE(
			    [ARPC] - [ARPC Prev Month],
			    [ARPC Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: cc65f493-e994-40cb-b628-4878e9904fa3

	measure '% High Value Customers' =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT(FactCustomerMetrics[ID]),
			        FactCustomerMetrics[Total_Spending] > 1000
			    ),
			    [Total Customers]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9261db58-32a1-48ba-a5bc-34362bdcda59

	measure '% Top Segment Revenue' =
			
			DIVIDE(
			    CALCULATE(
			        [Total Revenue],
			        DimCustomer[Age_segment] = "Mature"
			    ),
			    [Total Revenue]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 27c2844f-bb3c-463e-9052-daa6c3d856ad

	measure 'Total Income' = SUM(FactCustomerMetrics[Income])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 792366bf-1ec2-480c-a03d-4bd577dfa02c

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Avg Spending' = AVERAGE(FactCustomerMetrics[Total_Spending])
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 0b9091fb-7da8-4e38-9700-17e68baa95fb

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Top Product Revenue %' =
			
			DIVIDE(
			    MAXX(
			        VALUES('Product Category Table'[Category]),
			        [Revenue Selected Category]
			    ),
			    [Total Revenue]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: f851b2e4-19b8-4b07-bf58-d5e0e4e7470e

	measure 'Avg Purchase Value Prev Month' =
			
			CALCULATE(
			    [Avg Purchase Value],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 8b6e25f2-9185-46db-a8c2-adfe3ee47330

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Avg Purchase Value Variance' = [Avg Purchase Value] - [Avg Purchase Value Prev Month]
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: f7722c7c-9832-4dda-9601-0da89be20384

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% Avg Purchase Value Growth' =
			
			DIVIDE(
			    [Avg Purchase Value] - [Avg Purchase Value Prev Month],
			    [Avg Purchase Value Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1363bd79-0b13-4bfd-b55b-1e165fe24821

	measure 'High Value Transactions %' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(FactCustomerMetrics),
			        FactCustomerMetrics[Total_Spending] > 500
			    ),
			    COUNTROWS(FactCustomerMetrics)
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b3caa458-0395-46d9-9a81-bab925896675

	measure 'Revenue Concentration %' =
			
			VAR MaxRevenue =
			    MAXX(
			        {
			            [Revenue Wines],
			            [Revenue Meat],
			            [Revenue Gold],
			            [Revenue Fish],
			            [Revenue Fruits],
			            [Revenue Sweets]
			        },
			        [Value]
			    )
			RETURN
			DIVIDE(
			    MaxRevenue,
			    [Total Revenue]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 0a20d7f5-9cfe-46b8-8453-e18cac813adc

	measure 'Active Categories' =
			
			CALCULATE(
			    COUNTROWS(
			        FILTER(
			            {
			                [Revenue Wines],
			                [Revenue Meat],
			                [Revenue Gold],
			                [Revenue Fish],
			                [Revenue Fruits],
			                [Revenue Sweets]
			            },
			            [Value] > 0
			        )
			    )
			)
		formatString: 0
		lineageTag: af521085-f2ea-4e76-ace0-77a75f4dc38a

	measure 'Revenue Concentration % Prev Month' =
			
			CALCULATE(
			    [Revenue Concentration %],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d3d097f6-ee1d-4ce8-a354-2a82cf5f3b4e

	measure 'Revenue Concentration % Variance' = [Revenue Concentration %] - [Revenue Concentration % Prev Month]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 89d84ad9-1ccf-4dfe-8329-59902c721b14

	measure '% Revenue Concentration Growth' =
			
			DIVIDE(
			    [Revenue Concentration %] - [Revenue Concentration % Prev Month],
			    [Revenue Concentration % Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: db024b32-a1c9-44c9-bbd1-649155768fc7

	measure 'Top Product Revenue' =
			
			MAXX(
			    {
			        [Revenue Wines],
			        [Revenue Meat],
			        [Revenue Gold],
			        [Revenue Fish],
			        [Revenue Fruits],
			        [Revenue Sweets]
			    },
			    [Value]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: eee18120-33b9-475b-a832-e5972ea9a9aa

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Spending' = SUM(FactCustomerMetrics[Total_Spending])
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 75925073-0f2b-42d4-85a6-1d41ade8a2d2

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue % by Category' =
			
			DIVIDE(
			    [Revenue Selected Category],
			    [Total Revenue]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 744dfc17-d1d6-4358-8fe8-3859f655877f

	measure 'Category Rank' =
			
			RANKX(
			    ALL('Product Category Table'[Category]),
			    [Revenue Selected Category],
			    ,
			    DESC
			)
		formatString: 0
		lineageTag: ab1fad52-6eb0-42bb-8b46-ccd223bd4cb5

	measure 'Web Conversion Rate' =
			
			DIVIDE(
			    [Web Purchases],
			    SUM(FactCustomerMetrics[NumWebVisitsMonth]),
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9c27ec4d-ed06-444f-9a9a-3809311e7487

	measure 'Web Conversion Rate Prev Month' =
			
			CALCULATE(
			    [Web Conversion Rate],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 60540bcc-92b1-454f-8057-0c913a8edb7f

	measure 'Web Conversion Rate Variance' = [Web Conversion Rate] - [Web Conversion Rate Prev Month]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: edce83e1-8546-4b7a-864e-5cbd0f12c2f5

	measure '% Web Conversion Rate Growth' =
			
			DIVIDE(
			    [Web Conversion Rate] - [Web Conversion Rate Prev Month],
			    [Web Conversion Rate Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 193e30bb-5b1b-4c03-a247-11d6affa068d

	measure 'Total Purchases Prev Month' =
			
			CALCULATE(
			    [Total Purchases],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00
		lineageTag: ffd098dc-cbd3-494c-b637-53f6b5313c41

	measure 'Total Purchases Variance' = [Total Purchases] - [Total Purchases Prev Month]
		formatString: 0.00
		lineageTag: 2f837f1e-e9bb-4f24-9350-59bb7e3bcd45

	measure '% Total Purchases Growth' =
			
			DIVIDE(
			    [Total Purchases] - [Total Purchases Prev Month],
			    [Total Purchases Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7e3f53a9-2198-42fe-a155-ee221d88d026

	measure 'Web Purchase %' = ```
			
			DIVIDE(
			    [Web Purchases], 
			    [Total Purchases],
			    0
			    )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: fdc89140-9d78-482f-a4e3-083baf8ca9ed

	measure 'Store Purchase %' = ```
			
			DIVIDE(
			    [Store Purchases], 
			    [Total Purchases],
			    0
			    )
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 15a43028-d19e-4cfb-b660-7d6b319e3b23

	measure 'Catalog Purchase %' =
			
			DIVIDE(
			    [Catalog Purchases],
			    [Total Purchases],
			    0
			    )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 27885224-0a40-4029-adcb-4e9c6a581af8

	measure 'Top Channel %' =
			
			MAX(
			    MAX([Web Purchase %], [Store Purchase %]),
			    [Catalog Purchase %]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: a3deba42-5eba-4cc6-80c3-e958d357dd9e

	measure 'Top Channel % Prev Month' =
			
			CALCULATE(
			    [Top Channel %],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7c2c3529-5baa-4be0-ada8-2f549552204b

	measure 'Top Channel % Variance' = [Top Channel %] - [Top Channel % Prev Month]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 3b111833-6097-4e30-b00f-644c4ae529e8

	measure 'Top Channel % Growth' =
			
			DIVIDE(
			    [Top Channel %] - [Top Channel % Prev Month],
			    [Top Channel % Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d56cd501-70ed-45cf-831a-b6bd365e9d3e

	measure 'Top Channel Name' =
			
			VAR WebPct = [Web Purchase %]
			VAR StorePct = [Store Purchase %]
			VAR CatalogPct = [Catalog Purchase %]
			
			RETURN
			SWITCH(
			    TRUE(),
			    WebPct >= StorePct && WebPct >= CatalogPct, "Web",
			    StorePct >= WebPct && StorePct >= CatalogPct, "Store",
			    "Catalog"
			)
		lineageTag: 646ffa16-ac8a-496b-952e-97c81f3b0b19

	measure 'Purchases by Channel' =
			
			SWITCH(
			    SELECTEDVALUE('Channel Table'[Channel]),
			    "Web", SUM(FactCustomerMetrics[NumWebPurchases]),
			    "Store", SUM(FactCustomerMetrics[NumStorePurchases]),
			    "Catalog", SUM(FactCustomerMetrics[NumCatalogPurchases]),
			    "Deals", SUM(FactCustomerMetrics[NumDealsPurchases])
			)
		formatString: 0
		lineageTag: 2754c30e-1102-4f3d-94c2-884946cb1b9b

	measure 'Revenue by Channel' =
			
			SWITCH(
			    SELECTEDVALUE('Channel Table'[Channel]),
			    "Web", [Total Revenue] * [Web Purchase %],
			    "Store", [Total Revenue] * [Store Purchase %],
			    "Catalog", [Total Revenue] * [Catalog Purchase %],
			    "Deals", [Total Revenue] * [Deals Purchase %]
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: c3821158-1ff7-4bba-90cc-1fd7acfa0104

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Deals Purchase %' =
			
			DIVIDE(
			    [Deals Purchases],
			    [Total Purchases],
			    0
			    )
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 18dbdf0d-eebe-49aa-ad04-09b97d27126f

	measure 'Max Conversion' =
			
			MAXX(
			    ALLSELECTED(DimDate),
			    [Web Conversion Rate]
			)
		lineageTag: e2fc83fd-3712-4cb9-b7e7-88d3daa663be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Conversion' =
			
			MINX(
			    ALLSELECTED(DimDate),
			    [Web Conversion Rate]
			)
		lineageTag: d3928ce0-5ccc-4416-af1e-c0f6c7e6fbfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Point' =
			
			IF(
			    [Web Conversion Rate] = [Max Conversion],
			    [Web Conversion Rate],
			    BLANK()
			)
		lineageTag: cee4347f-843f-41cd-af97-f219e886f17b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Point' =
			
			IF(
			    [Web Conversion Rate] = [Min Conversion],
			    [Web Conversion Rate],
			    BLANK()
			)
		lineageTag: 9de08e98-6b33-47e3-999a-db388860ab62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Targeted Customers' =
			
			CALCULATE(
			    DISTINCTCOUNT(FactCustomerMetrics[ID]),
			    FactCustomerMetrics[TotalCampaignAccepted] > 0
			)
		formatString: 0
		lineageTag: 9e5b92c8-6919-4e8d-ae9d-4d35299638bf

	measure 'Revenue per Responder' =
			
			DIVIDE(
			    [Revenue Campaign Responders],
			    [Campaign Responses],
			    0
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: c428fb35-d08c-4779-bc62-044945b54e8d

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% Revenue from Responders' =
			
			DIVIDE(
			    [Revenue Campaign Responders],
			    [Total Revenue],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7e9e43b3-9680-4134-ac9e-730d9b3376a4

	measure 'Revenue Campaign Responders Prev Month' =
			
			CALCULATE(
			    [Revenue Campaign Responders],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 945b930a-1082-42b7-8756-b8ee77112bc5

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue Campaign Responders Variance' = [Revenue Campaign Responders] - [Revenue Campaign Responders Prev Month]
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 17fad30c-0655-403f-9453-36833a50c087

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue per Responder Prev Month' =
			
			CALCULATE(
			    [Revenue per Responder],
			    DATEADD(
			        DimDate[Date],
			        -1,
			        MONTH
			    )
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 588ae0d0-c362-49c4-8fd4-862d2917560a

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue per Responder Variance' = [Revenue per Responder] - [Revenue per Responder Prev Month]
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 73373a25-d9be-4a08-a04b-ab34782a5a32

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure '% Revenue per Responder Growth' =
			
			DIVIDE(
			    [Revenue per Responder] - [Revenue per Responder Prev Month],
			    [Revenue per Responder Prev Month],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: a7bed67f-fbe4-4f6f-a6da-92f9959febfc

	measure 'High Value Responders %' =
			
			DIVIDE(
			    CALCULATE(
			        COUNTROWS(FactCustomerMetrics),
			        FactCustomerMetrics[Response] = 1,
			        FactCustomerMetrics[Total_Spending] > 500
			    ),
			    [Campaign Responses],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1d002075-671c-43a8-9142-f137ff6dc69a

	measure 'Campaign Responses Dynamic' =
			
			SWITCH(
			    SELECTEDVALUE('Campaign Table'[Campaign]),
			    "Campaign 1", SUM(FactCustomerMetrics[AcceptedCmp1]),
			    "Campaign 2", SUM(FactCustomerMetrics[AcceptedCmp2]),
			    "Campaign 3", SUM(FactCustomerMetrics[AcceptedCmp3]),
			    "Campaign 4", SUM(FactCustomerMetrics[AcceptedCmp4]),
			    "Campaign 5", SUM(FactCustomerMetrics[AcceptedCmp5])
			)
		formatString: 0
		lineageTag: af4b38e5-2654-45bc-8c20-439abd4c25d2

	measure 'Targeted by Campaign' = ```
			
			SWITCH(
			    SELECTEDVALUE('Campaign Table'[Campaign]),
			    
			    "Campaign 1",
			        CALCULATE(
			            DISTINCTCOUNT(FactCustomerMetrics[ID]),
			            FactCustomerMetrics[AcceptedCmp1] IN {0,1}
			        ),
			
			    "Campaign 2",
			        CALCULATE(
			            DISTINCTCOUNT(FactCustomerMetrics[ID]),
			            FactCustomerMetrics[AcceptedCmp2] IN {0,1}
			        ),
			
			    "Campaign 3",
			        CALCULATE(
			            DISTINCTCOUNT(FactCustomerMetrics[ID]),
			            FactCustomerMetrics[AcceptedCmp3] IN {0,1}
			        ),
			
			    "Campaign 4",
			        CALCULATE(
			            DISTINCTCOUNT(FactCustomerMetrics[ID]),
			            FactCustomerMetrics[AcceptedCmp4] IN {0,1}
			        ),
			
			    "Campaign 5",
			        CALCULATE(
			            DISTINCTCOUNT(FactCustomerMetrics[ID]),
			            FactCustomerMetrics[AcceptedCmp5] IN {0,1}
			        )
			)
			```
		formatString: 0
		lineageTag: fdb93472-eeb6-44ec-93b0-0c2a9e38f393

	measure 'Campaign Conversion Rate Dynamic' =
			
			DIVIDE(
			    [Campaign Responses Dynamic],
			    [Targeted by Campaign],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: a39e2942-6f1f-4314-96c5-ec9131c210a7

	measure 'Campaign Responses Total' =
			
			SUM(FactCustomerMetrics[AcceptedCmp1]) +
			SUM(FactCustomerMetrics[AcceptedCmp2]) +
			SUM(FactCustomerMetrics[AcceptedCmp3]) +
			SUM(FactCustomerMetrics[AcceptedCmp4]) +
			SUM(FactCustomerMetrics[AcceptedCmp5])
		formatString: 0
		lineageTag: da2988e3-34c6-467c-9051-d7084ab02432

	measure 'Revenue by Campaign' = ```
			
			[Total Revenue] * 
			DIVIDE(
			    [Campaign Responses],
			    [Campaign Responses Total]
			)
			```
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: bc5968a2-720b-4552-895c-2337aa212ce7

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Revenue per Responder Dynamic' =
			
			DIVIDE(
			    [Revenue by Campaign],
			    [Campaign Responses Dynamic],
			    0
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: 95352833-40eb-4f30-8232-4624abb6e83d

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	measure 'Avg Campaign Conversion Rate Dynamic' =
			
			AVERAGEX(
			    ALLSELECTED('Campaign Table'[Campaign]),
			    [Campaign Conversion Rate Dynamic]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 01b62f23-e327-4673-b051-03dcbdaa2018

	measure 'Avg Revenue per Responder Dynamic' =
			
			AVERAGEX(
			    ALLSELECTED('Campaign Table'[Campaign]),
			    [Revenue per Responder Dynamic]
			)
		formatString: "S/"\ #,0.00;-"S/"\ #,0.00;"S/"\ #,0.00
		lineageTag: da4e4060-93db-4827-9375-d039ba06ccf0

		annotation PBI_FormatHint = {"currencyCulture":"es-PE"}

	partition Measures_Table = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

